-- ═══════════════════════════════════════════════════════════════
-- Corolas Supabase Auth Schema — Updated 2026
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor)
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. PROJECTS TABLE ───
-- Stores all Corolas projects with platform/application categorization

create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text not null unique,
  category text not null check (category in ('platform', 'application')),
  domain text not null,
  logo_url text,
  short_description text not null default '',
  full_description text not null default '',
  features jsonb default '[]'::jsonb,
  status text not null default 'active' check (status in ('active', 'inactive', 'development')),
  display_order integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.projects enable row level security;

-- Public read access for projects
create policy "Projects are publicly viewable"
  on public.projects for select
  to anon, authenticated
  using (status = 'active');

-- Only admins can manage projects
create policy "Admins can manage projects"
  on public.projects for all
  to authenticated
  using (auth.jwt()->>'role' = 'admin')
  with check (auth.jwt()->>'role' = 'admin');

-- ─── 2. PROFILES TABLE ───
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Users can view own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Public profiles are viewable"
  on public.profiles for select
  to anon
  using (true);

-- ─── 3. AUTO-CREATE PROFILE TRIGGER ───
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture',
      new.raw_user_meta_data->>'avatar'
    )
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ─── 4. CONTACT SUBMISSIONS TABLE ───
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.contact_submissions enable row level security;

create policy "Allow anonymous contact submissions"
  on public.contact_submissions for insert
  to anon
  with check (true);

create policy "Authenticated users can read submissions"
  on public.contact_submissions for select
  to authenticated
  using (true);

-- ─── 5. STORAGE: AVATAR + PROJECT LOGO BUCKET ───
insert into storage.buckets (id, name, public)
values ('profiles', 'profiles', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('project-logos', 'project-logos', true)
on conflict (id) do nothing;

-- Storage policies for profiles
create policy "Authenticated users can upload avatars"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'profiles');

create policy "Users can update own avatar"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'profiles');

create policy "Avatar images are publicly accessible"
  on storage.objects for select
  to anon
  using (bucket_id = 'profiles');

-- Storage policies for project logos (admin only for write, public for read)
create policy "Authenticated users can upload project logos"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'project-logos');

create policy "Authenticated users can update project logos"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'project-logos');

create policy "Project logos are publicly accessible"
  on storage.objects for select
  to anon
  using (bucket_id = 'project-logos');

-- ─── 6. SEED DATA — INITIAL PROJECTS ───
-- Insert existing Corolas projects

insert into public.projects (name, slug, category, domain, logo_url, short_description, full_description, status, display_order)
values
  ('Platonic', 'platonic', 'platform', 'platonic.corolas.top', '/images/platonic-logo.png', 'Exploring the boundaries of AI-driven creativity and digital expression.', 'This section is reserved for the Platonic project description. Customize this in the admin console to describe what Platonic does, its mission, and key features. Add technical details, use cases, or roadmap information.', 'active', 1),
  ('Yhea', 'yhea', 'platform', 'yhea.corolas.top', '/images/yhea-logo.png', 'Intelligent systems for the modern web.', 'This section is reserved for the Yhea project description. Customize this in the admin console to describe what Yhea does, its mission, and key features.', 'active', 2),
  ('Thea', 'thea', 'application', 'thea.corolas.top', '/images/thea-logo.png', 'Advanced analytics and insights platform.', 'This section is reserved for the Thea project description. Customize this in the admin console to describe what Thea does, its mission, and key features.', 'active', 3)
on conflict (slug) do nothing;

-- ─── 7. ADMIN CONFIGURATION NOTES ───
-- For the admin console (corolar.corolas.top):
--
-- The admin system uses a SEPARATE Supabase project for data isolation.
-- Set these environment variables in Vercel:
--   VITE_ADMIN_SUPABASE_URL=https://your-admin-project.supabase.co
--   VITE_ADMIN_SUPABASE_PUBLISHABLE_KEY=eyJhbG...
--
-- Admin users are created manually via Supabase Dashboard SQL Editor
-- on the ADMIN Supabase project:
--
--   insert into public.admins (username, password_hash, role)
--   values (
--     'corolas',
--     '$2a$10$...',  -- bcrypt hash of your password
--     'superadmin'
--   );
--
-- AI agents are also created manually:
--
--   insert into public.ai_agents (name, api_key, password_hash, permissions, is_active)
--   values (
--     'Assistant AI',
--     'ca_xxxxxxxx',
--     '$2a$10$...',  -- bcrypt hash
--     '{"projects": true, "users": true, "oauth": false}',
--     true
--   );
--
-- Authentication → URL Configuration
--    Site URL: https://www.corolas.top
--    Redirect URLs: https://www.corolas.top/**
--
-- Authentication → Providers → Email
--    - Enable Email Provider
--    - Confirm email: ON
--    - Secure email change: ON
--    - OTP expiry: 3600
