-- ═══════════════════════════════════════════════════════════════
-- Corolas Supabase Auth Schema
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor)
-- ═══════════════════════════════════════════════════════════════

-- ─── 1. PROFILES TABLE ───
-- Stores public user profile data linked to auth.users

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Enable Row Level Security
alter table public.profiles enable row level security;

-- RLS Policies: users can only read/update their own profile
create policy "Users can view own profile"
  on public.profiles for select
  to authenticated
  using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Allow anon read for public profiles (optional - remove if you want full privacy)
create policy "Public profiles are viewable"
  on public.profiles for select
  to anon
  using (true);


-- ─── 2. AUTO-CREATE PROFILE TRIGGER ───
-- Automatically creates a profile row when a new user signs up

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture',
      new.raw_user_meta_data->>'avatar'
    )
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop existing trigger if recreating
drop trigger if exists on_auth_user_created on auth.users;

-- Create trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ─── 3. CONTACT SUBMISSIONS TABLE ───
-- Stores contact form submissions

create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.contact_submissions enable row level security;

-- Allow anyone to submit (public contact form)
create policy "Allow anonymous contact submissions"
  on public.contact_submissions for insert
  to anon
  with check (true);

-- Only authenticated users can read (admin use)
create policy "Authenticated users can read submissions"
  on public.contact_submissions for select
  to authenticated
  using (true);


-- ─── 4. STORAGE: AVATAR BUCKET ───
-- Create storage bucket for user avatars

insert into storage.buckets (id, name, public)
values ('profiles', 'profiles', true)
on conflict (id) do nothing;

-- Storage RLS: users can only upload to their own folder
create policy "Users can upload own avatar"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'profiles' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users can update own avatar"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'profiles' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Avatar images are publicly accessible"
  on storage.objects for select
  to anon
  using (bucket_id = 'profiles');


-- ─── 5. AUTH CONFIGURATION NOTES ───
-- Complete these steps in Supabase Dashboard:
--
-- 1. Authentication → Providers → Email
--    - Enable Email Provider
--    - Check "Confirm email" (REQUIRED for security)
--    - Set "Secure email change" to true
--    - Set OTP expiry to 3600 seconds (1 hour)
--
-- 2. Authentication → URL Configuration
--    - Site URL: https://www.corolas.top
--    - Redirect URLs: https://www.corolas.top/**
--
-- 3. Authentication → Providers → Google
--    - Enable Google
--    - Enter Client ID and Secret from Google Cloud Console
--
-- 4. Authentication → Providers → Discord
--    - Enable Discord
--    - Enter Client ID and Secret from Discord Developer Portal
--
-- 5. Authentication → Providers → GitHub
--    - Enable GitHub
--    - Enter Client ID and Secret from GitHub Developer Settings
--
-- 6. Project Settings → Auth → SMTP (Production!)
--    - Configure custom SMTP (Resend/SendGrid/Mailgun)
--    - Sender email: noreply@corolas.top
--    - This ensures emails don't go to spam
